### ISSUE TITLE
create single yaml file for all parameters/operation

### ISSUE THREAD

**Issue by kbhawkey** [annegentle/wadl2rst#18]
Create a single yaml file per operation that defines request, response, header parameters.
Use this file to declaratively define the parameter tables in rst.
Example:
description: "The UUID of the tenant in a multi-tenancy cloud."
      format: ""
      in: "path"
      name: "tenant_id"
      required: true  // change to optional?
      type: "string"
Also, in fields defined as: body, path, header, query.

**Comment by sdague** [comment]
What is "format" in this list?

Also, because it's yaml, the strings are auto quoted so sample is a little more like:

```
tenant_id:
    required: true
    in: path
    type: string
    description: |
        The UUID of the tenant in a multi-tenancy cloud.

```

This will let us lookup by tenant_id very easily (basically it brings the name up)

Also yaml supports long text blocks with newlines with the : | stanza
